### PR TITLE
adding in code block

### PR DESCRIPTION
**Pull request by solomon71**
for highlighting using highlightjs

Test URLs:
- Before: https://main--tbx-gtk--solomon71.hlx.page/drafts/pauls/test1
- After: https://codeblock--tbx-gtk--solomon71.hlx.page/drafts/pauls/test1

### CODE REVIEW

**Comment by solomon71** [comment]
@kyle-tbx - can you review this?

**Comment by kyle-tbx** [comment]
> @kyle-tbx - can you review this?

Hah, the first type of block I ended up creating to get familiar with the process was also a code block. Actually, two different blocks: one without syntax highlighting that allows optionally displaying line numbers, and one with highlighting including an optional dark mode theme and specifying a language.

I can break mine up into separate branches if we want to compare and choose which code block we want to use?

**Comment by solomon71** [comment]
submit PRs for these, so we can look at them

**Comment by solomon71** [comment]
not merging, we have a lighter solution

**Pull request closed without merging**
